# Generated by Django 4.2.2 on 2023-06-28 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='%Y/%m/%d'),
        ),
    ]
